import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { cookies } from "next/headers";


export const metadata: Metadata = {
  title: "Syfer's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cookies().get('theme')?.value ?? ""}>
      <body>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
